///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAsset {
  AppAsset._();

  static const String appleLogo = 'assets/icons/apple_logo.svg';
  static const String googleLogo = 'assets/icons/google_logo.svg';
  static const String kakaoLogo = 'assets/icons/kakao_logo.svg';
  static const String naverLogo = 'assets/icons/naver_logo.svg';
}
