name: mvp_provider_boilerplate
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.8.1
  provider: ^6.1.4
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  intl: ^0.19.0
  permission_handler: ^11.4.0
  logger: ^2.5.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/fonts/pretendard/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/lottie/
    - assets/json/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 800
